name: WRLDPaymentsAPI
version: 0.3.1
authors: [Jacob, ArkDev]
main: com.nftworlds.wallet.NFTWorlds
api-version: 1.17
softdepend:
  - Geyser-Spigot

commands:
  wallet:
    description: Open a GUI with information about your player balance.
    usage: /wallet
    permission: wrldpaymentsapi.wallet
    default: true